language: ruby
branches:
  only:
    - main
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: UDYo18eLWbGxfcLBxoyHXWUz+pkRXpuvUwkmoDqRDgYTrxGW4x3E7e+S7U/+tuJJDrIOWbxHxC2p++8SSpWpe8bC9i65Lu5ll92D6fak3UT11o6MBgAFyEENFN5JvHNcFTxDRVVqVRlzw6txv0lDPeDdM3sqCkNuJDSg3Ga/B8y/dCuzTRzikqBctOa9rAtHK2tWpretmP89FFZcTAFbQ7euyZfswhJuOzGsdD6WEcIsJL0QpLAlJW0F/TJnNQGzPx+0xBUko2PpNR7o8I6ZEdnhxSyt6YP70S8yrfLayJlvZbNySFBy9vuvaiIbgbXdhgZZAA8Lum6npem/02FBWwfQqlGV25xZV/IJ+UIzDq73jR6dHCfovAYDnn+RwQKCxYlTF//6wv3cA/TSn29su9cvhgHG/cdOcD1SkHEKZdr6gRZ25nHyyra/UTJ4ptJ266FRHviDXiXB/O5EgRXyNEEsMajzIXGJV5D3Fji/S/zwoSvLRYTKLYz7IgJsJ688MxqjL8EfA2nUq6C5CY1pgctlIOwD/PvFtys47eOamOc5Ecv4YsG/7M9b+fvA509a/8ILVx9S291Zc/ZguNeKcNNOqaHJRnCg+xB793LDkunl7uSVaHOyz2Pmm1E/qT9CXmVmGXHtCmaE7IkNrfqg1YPUa2r5Zq/gkoErBfNVDOs=
