language: ruby
branches:
  only:
    - master
before_script:
  - chmod +x deploy.sh
script:
  - bundle exec jekyll build
  - "./deploy.sh"
env:
  global:
    secure: yynMs+ZfVEXocyybZ5C6bqcEZ+56VOrpJWZ8Lf1Gtf5a0euVcM6HLJbzllxMiZcEUwsCV9vbEPwA42zW6VIAxuFe4ZBCYXjk0qG+aN7FW67N1oLPUVk3g/E21Q5vJvVXnmCrH3ZuvGpGgJQ4A4JkqH0n1FQblA5m/h2dXtxjeqx+utLQeJ4DRzBtjg2mIo7yTEdPyv0AusTn7fzBAalJrHALyn7MOdMCEr6hQ+Y2+T7loPhnCI9+h2pIsS2n/rCuefcTY4ckUNDeF46MzlXQe6TQmYEFfHf47eVmr0khI99x4Nx3w8egAdaQJk1Ysw9NZqzf6Uw+rKZUvQlFU4shkokh6pgKLKRKOHZgHC0Ozjhy9eJTFmB8nu3rDzlTxPB94FEEZ8faYTAqNjkMAL1/pdXrSd4WLKqUD8sKqsgGWDcw57bjrG1DgUqk4fPMRuDdVN/Io+P+Eg4igQkjNhmlF35hGGbY2IXQ9ZUIb5i6ET/YpmvMh7Gt0eOjR8q6kEd+0j/y+a2PiOlLyNo2zRqP4RlzO6W9+sK4DwOvydxYp4veWkaPYZ8Q5rCKMiHjCgANL44CFLZe0jxdPSMeNO+mLtNfPaBr4Cglr8OqdcnkQNqhAH0gDSWtISeBgNnt51v9b3kuGRE6D7qjd4rYaJDoRTzjPFZghXsCkGBES9GLv78=
