name: Jekyll site CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build jekyll project
      uses: jerryjvl/jekyll-build-action@v1
      
    #- name: Deploy to site repository
    # run: "./deploy.sh"
